dist: trusty
sudo: false
git:
  depth: false
addons:
  sonarcloud:
    organization: lucacappelletti94-github
    token:
      secure: EAfv07Q81y37JqCdw2o/+VHnAEIH5XOKUQz2n+DFYThHtmL3JkfL7tf/bkgF+v+IBfqtm0iwSk63DY8UOYNWa/tK9sC/GXRZxHnmEvJ3KKwK81tjl5jLcKYHqKshD68/+Us4nplNpRKiSPoUGX8miHnGNQyYuvLqd3RzfbK2inbCN9bGj/tDkc+1CD/HRBHL/13bXyI0Nw+wJCz3bALpkthn08ktWZZZvJz3EzHA8ZHzgcjifXAg+RVFlQ4OxgZssyBVnGccTAxFQKorxNCASe5Alv2YF1gmY22H0p7xJvsEdTag9owEr0iFfIqbxBd97zBmp8xBggur2XoYxgbBJpVcnReTfRNqgeDn5DYq+lgyTI4ebfBhdAcnOKmUFd11tslVgRn0NhmXbXJ0GmmTrZ12VQNBNbfNI+ax1fdsRWq79m8EONYX4cchqRrmBcJJ/pqVuvVwTCboNbzhOiP5C395fbhtv6nxf9Yy/DyUFfVs2DukCjgYCrESP0y1wBDe5elxImgr7sYcrpdA/MdYIlJIl7tBn7bErBX8+CwI8CAmfPAk5IufupThxtU/yo8ndustg67rbjWf9qj2kuvGWZjaNL3FuER0BnDZSA2oLDoi4NKgMGSjE+qVmIEp8FYu1zO4N2ZchgKSWbqCEV6MiiP0I5KvI9eDPEItXw1nbPg=
language: python
python:
- '3.6'
before_install:
- pip install --upgrade pytest
install:
- pip install .[test]
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
script:
- rm -rf .coverage
- coverage erase
- pytest --cov=sanitize_ml_label --cov-report xml:coverage.xml
- coverage combine --append || true
- coverage report
- coverage xml
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then sonar-scanner; fi
after_success:
- coveralls
- python-codacy-coverage -r coverage.xml
env:
  global:
  - secure: iLHVHfzPCw2fqCB7z+47Cbkn1ty5rID7uEVspGUOp5SxcLh+RSoETBworYJdq8piQqP4eB4vidFGQI0fEAI87fiKS+6Op4GnZ+UgW0I62uShMM2kD4ATC0r8G78Jh9FTcQhpzuGnh4DcI0VF5Tz41CBaAJ1QAm5NnuKCc24qn1TVm/yDa5dGmTHjy4ij1E6aTJ4xwI/NHQmC6YCVcfqF45wIlIK6yP3yNLY+Jje7Ky61Tf8JpMAJ0SeN3mAJ2ziD+4LYKYL8aX2HFPPF01rSZF/7LCLvlYZ+GWZSyF48cpS8ZGE5zmQpVV8WrMYVLdwP0g6iLHOevwpoOTVkCUq7mjDRA0GBVL4sTlGUEU+7bz/QT1KHVuqNT5oEugFy2l7w7qbNm+tgqWK3u6uGXbwyOA6bpb6n7nHWyq99uHGbhei8bwyCmHer55WSUuVx+z706c/30BJORUIXLlxFTBBSgDWgrpnbhGf2vYV5mvWlchBXw2Ewr2/6fD5ayhi86F7wGrPkeoFgAGiFy0mQKKZ99ACE1GTe71GnYGcoZ/9yXI66sVuFKq0HuPbPGLl9iXA2NUl/jxr8vjuS8HX+fRj8MiYQWa3/UtbdGGV2BWEeD31+gZ79hNOcehqkUbOEkdDAN2b3Xh03jxcgNlIeEFPZX5BMWM7MLpKkn9kv+Ha4tuo=
  - secure: Xe1XqrZG8NbVvFkVpSLE2f9fNOfAwKsVa7pu5444jjRTOQEU4rLLkn3lo5B9KrIRyGyvxUHCYeV9WSyqGr4R+D1vHpY+Ec0bHQlMweW05F+lPgvAYTJhwHIvawee/UmB/OcSiUjgjz57zz3CISyRfx5qrU32OXbZnXQadGmYRo7S6OedP9oD1WYLCnESm2cJtCEovharvzRs0Yt9UdHVgX7n8FnlkVgiUuiFiopGOhR49Bt3IpYvwwi77kwF7RWCJjutTRnnIw8q5Ac0V8SpPpQRR37qohCZlpQbJZCpK9GnQ0u0QaloH5C4N9mSJNEZcYF5Qq/NEnt9xmZwymPDEGGs4xSLDrxPrEGZ/at9UrldLPBzwWmieIhvHEJUZzy1TV6oA2eMO/f2vMgf9PlnmUpW4Da6gbiX+an4x84JY+njsh/EL4y9O8hELM/C+2dVo7NDCCx4h8Zx7z9a8mDMFUYFKGMtXosY84+FLcRz6PO47bxD8Ezgi5dXIYcET5ynPXBNq0G0kuicYJXgFNiMz5OCjpZKi3+a3VqpJRB9DdOrnRiyMgfbMyrUmx+r0By0hp0INDQnS6XBgGOwG8hq6vU4W6Yxck/KPDqt2ZT/diTIxDuvpFnPUh27ToEaTH73tXfuxx9wCNQbmXJaV4iDzlKYt2kY3hhSc5t2j3TvmBc=
